version: '3.7'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: express-app_api
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - db
    networks:
      - app

  db:
    image: mongo
    container_name: express-app_db
    networks:
      - app


networks:
  app: